apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: dock1998/python_custom:v1
    name: test
    command: 
     - /bin/bash
     - -c
     - |
       echo `date` >> /data/file2.txt &&
       tail -f /dev/null
    volumeMounts:
    - mountPath: /data
      name: hostpath-privileged
  volumes:
    - name: hostpath-privileged
      persistentVolumeClaim:
        claimName: postgres-pv-claim